import pandas as pd


class Data:
    numPatients = 0
    studyID = pd.Series([])
    # Edit the following names for different file names:
    # Demographics, Cormobidities:
    age = pd.Series([])
    cirrhosisStatus = pd.Series([])
    cancerStat = pd.Series([])
    esrd = pd.Series([])
    # immunoSup = pd.Series([])
    comaVisual = pd.Series([])
    comaVerbal = pd.Series([])
    comaMotor = pd.Series([])
    organtx = pd.Series([])
    sct = pd.Series([])
    hiv = pd.Series([])
    cd4 = pd.Series([])
    prednisone = pd.Series([])
    pred_dose = pd.Series([])
    # Pulse:
    pulseHigh = pd.Series([])
    pulseLow = pd.Series([])
    # Blood Pressure:
    bpHigh = pd.Series([])
    bpLow = pd.Series([])
    # Temperature:(
    temperatureHigh = pd.Series([])
    temperatureLow = pd.Series([])
    # Respiratory Rate:
    respRateHigh = pd.Series([])
    respRateLow = pd.Series([])
    # pO2, A-aDo2, Mech Vent,
    pO2High = pd.Series([])
    pO2Low = pd.Series([])
    isMechVent = pd.Series([])
    fiO2High = pd.Series([])
    fiO2Low = pd.Series([])
    pCO2High = pd.Series([])
    pCO2Low = pd.Series([])
    # Hematocrit:
    hctHigh = pd.Series([])
    hctLow = pd.Series([])
    # WBC:
    wbcHigh = pd.Series([])
    wbcLow = pd.Series([])
    # Serum Sodium:
    naHigh = pd.Series([])
    naLow = pd.Series([])
    # Serum Albumin:
    albHigh = pd.Series([])
    albLow = pd.Series([])
    # Serum Bilirubin:
    bilirubinLevel = pd.Series([])
    # Serum Glucose:
    glucHigh = pd.Series([])
    glucLow = pd.Series([])
    # Serum BUN (Blood Urea Nitrogen):
    bunHigh = pd.Series([])
    bunLow = pd.Series([])
    # Acute Renal Failure Testing:
    # Always take high on Creatinine on Day 0
    crHigh = pd.Series([])
    crLow = pd.Series([])
    urineOut = pd.Series([])
    # pH and pCO2:
    # lowest ph highest co2
    pCO2pH = pCO2Low
    pHLow = pd.Series([])

    # Day 0 / Day 1 for missing
    lo_wbc_d0 = pd.Series([])
    hi_wbc_d0 = pd.Series([])
    lo_wbc_d1 = pd.Series([])
    hi_wbc_d1 = pd.Series([])

    lo_hct_d0 = pd.Series([])
    lo_hct_d1 = pd.Series([])
    hi_hct_d0 = pd.Series([])
    hi_hct_d1 = pd.Series([])
    lo_alb_d1 = pd.Series([])
    hi_alb_d1 = pd.Series([])
    urine_out_d1 = pd.Series([])
    lo_urea_d1 = pd.Series([])
    hi_urea_d1 = pd.Series([])
    lo_gluc_d1 = pd.Series([])
    hi_gluc_d1 = pd.Series([])
    tbil_d1 = pd.Series([])
    intubated_8am_d1 = pd.Series([])

    list = []
    title_list = []

    def __init__(self, CSV_file):  # For manual entry add titles parameter to constructor
        self.numPatients = len(CSV_file['study_id'])
        self.studyID = pd.Series(CSV_file['study_id'])
        self.age = pd.Series(CSV_file['age'])
        self.cirrhosisStatus = pd.Series(CSV_file['cirr'])
        self.cancerStat = pd.Series(CSV_file['cancer'])
        self.esrd = pd.Series(CSV_file['esrd'])
        # self.immunoSup = pd.Series(CSV_file['immunocomp'])
        self.comaVisual = pd.Series(CSV_file['lo_gcs_visual_d0'])
        self.comaVerbal = pd.Series(CSV_file['lo_gcs_verbal_d0'])
        self.comaMotor = pd.Series(CSV_file['lo_gcs_motor_d0'])
        self.pulseHigh = pd.Series(CSV_file['hi_hr_24h'])
        self.pulseLow = pd.Series(CSV_file['lo_hr_24h'])
        self.bpHigh = pd.Series(CSV_file['hi_map_24h'])
        self.bpLow = pd.Series(CSV_file['lo_map_24h'])
        self.temperatureHigh = pd.Series(CSV_file['hi_temp_24h'])
        self.temperatureLow = pd.Series(CSV_file['lo_temp_24h'])
        self.respRateHigh = pd.Series(CSV_file['hi_rr_24h'])
        self.respRateLow = pd.Series(CSV_file['lo_rr_24h'])
        self.pO2High = pd.Series(CSV_file['hi_po2_24h'])
        self.pO2Low = pd.Series(CSV_file['lo_po2_24h'])
        self.isMechVent = pd.Series(CSV_file['intubated_8am_d0'])
        self.fiO2High = pd.Series(CSV_file['abg_hi_fio2_24h'])
        self.fiO2Low = pd.Series(CSV_file['abg_lo_fio2_24h'])
        self.pCO2High = pd.Series(CSV_file['ph_hi_co2_d0'])
        self.pCO2Low = pd.Series(CSV_file['ph_lo_co2_d0'])
        self.hctHigh = pd.Series(CSV_file['hi_hct_24h'])
        self.hctLow = pd.Series(CSV_file['lo_hct_24h'])
        self.wbcHigh = pd.Series(CSV_file['hi_wbc_24h'])
        self.wbcLow = pd.Series(CSV_file['lo_wbc_24h'])
        self.naHigh = pd.Series(CSV_file['hi_na_24h'])
        self.naLow = pd.Series(CSV_file['lo_na_24h'])
        self.albHigh = pd.Series(CSV_file['hi_alb_d0'])
        self.albLow = pd.Series(CSV_file['lo_alb_d0'])
        self.bilirubinLevel = pd.Series(CSV_file['tbil_d0'])
        self.glucHigh = pd.Series(CSV_file['hi_gluc_d0'])
        self.glucLow = pd.Series(CSV_file['lo_gluc_d0'])
        self.bunHigh = pd.Series(CSV_file['hi_urea_d0'])
        self.bunLow = pd.Series(CSV_file['lo_urea_d0'])
        self.crHigh = pd.Series(CSV_file['hi_cr_24h'])
        self.crLow = pd.Series(CSV_file['lo_cr_24h'])
        self.urineOut = pd.Series(CSV_file['urine_out_d0'])
        self.pHLow = pd.Series(CSV_file['lo_ph_24h'])
        self.organtx = pd.Series(CSV_file['organtx'])
        self.sct = pd.Series(CSV_file['sct'])
        self.hiv = pd.Series(CSV_file['hiv'])
        self.cd4 = pd.Series(CSV_file['cd4'])
        self.prednisone = pd.Series(CSV_file['prednisone'])
        self.pred_dose = pd.Series(CSV_file['pred_dose'])

        # FOR NWH THESE NEED TO BE DISABLED
        self.lo_wbc_d0 = pd.Series(CSV_file['lo_wbc_d0'])
        self.hi_wbc_d0 = pd.Series(CSV_file['hi_wbc_d0'])
        self.lo_wbc_d1 = pd.Series(CSV_file['lo_wbc_d1'])
        self.hi_wbc_d1 = pd.Series(CSV_file['hi_wbc_d1'])
        self.lo_hct_d0 = pd.Series(CSV_file['lo_hct_d0'])
        self.lo_hct_d1 = pd.Series(CSV_file['lo_hct_d1'])
        self.hi_hct_d0 = pd.Series(CSV_file['hi_hct_d0'])
        self.hi_hct_d1 = pd.Series(CSV_file['hi_hct_d1'])
        self.lo_alb_d1 = pd.Series(CSV_file['lo_alb_d1'])
        self.hi_alb_d1 = pd.Series(CSV_file['hi_alb_d1'])
        self.urine_out_d1 = pd.Series(CSV_file['urine_out_d1'])
        self.lo_urea_d1 = pd.Series(CSV_file['lo_urea_d1'])
        self.hi_urea_d1 = pd.Series(CSV_file['hi_urea_d1'])
        self.lo_gluc_d1 = pd.Series(CSV_file['lo_gluc_d1'])
        self.hi_gluc_d1 = pd.Series(CSV_file['hi_gluc_d1'])
        self.tbil_d1 = pd.Series(CSV_file['tbil_d1'])
        self.intubated_8am_d1 = pd.Series(CSV_file['intubated_8am_d1'])

        self.list.append(self.studyID)
        self.list.append(self.age)
        self.list.append(self.cirrhosisStatus)
        self.list.append(self.cancerStat)
        self.list.append(self.esrd)
        # self.immunoSup = pd.Series(CSV_file['immunocomp'])
        self.list.append(self.comaVisual)
        self.list.append(self.comaVerbal)
        self.list.append(self.comaMotor)
        self.list.append(self.pulseHigh)
        self.list.append(self.pulseLow)
        self.list.append(self.bpHigh)
        self.list.append(self.bpLow)
        self.list.append(self.temperatureHigh)
        self.list.append(self.temperatureLow)
        self.list.append(self.respRateHigh)
        self.list.append(self.respRateLow)
        self.list.append(self.pO2High)
        self.list.append(self.pO2Low)
        self.list.append(self.isMechVent)
        self.list.append(self.fiO2High)
        self.list.append(self.fiO2Low)
        self.list.append(self.pCO2High)
        self.list.append(self.pCO2Low)
        self.list.append(self.hctHigh)
        self.list.append(self.hctLow)
        self.list.append(self.wbcHigh)
        self.list.append(self.wbcLow)
        self.list.append(self.naHigh)
        self.list.append(self.naLow)
        self.list.append(self.albHigh)
        self.list.append(self.albLow)
        self.list.append(self.bilirubinLevel)
        self.list.append(self.glucHigh)
        self.list.append(self.glucLow)
        self.list.append(self.bunHigh)
        self.list.append(self.bunLow)
        self.list.append(self.crHigh)
        self.list.append(self.crLow)
        self.list.append(self.urineOut)
        self.list.append(self.pHLow)
        self.list.append(self.organtx)
        self.list.append(self.sct)
        self.list.append(self.hiv)
        self.list.append(self.cd4)
        self.list.append(self.prednisone)
        self.list.append(self.pred_dose)

        # d0 d1 stuff:
        self.list.append(self.lo_wbc_d0)
        self.list.append(self.hi_wbc_d0)
        self.list.append(self.lo_wbc_d1)
        self.list.append(self.hi_wbc_d1)
        self.list.append(self.lo_hct_d0)
        self.list.append(self.lo_hct_d1)
        self.list.append(self.hi_hct_d0)
        self.list.append(self.hi_hct_d1)
        self.list.append(self.lo_alb_d1)
        self.list.append(self.hi_alb_d1)
        self.list.append(self.urine_out_d1)
        self.list.append(self.lo_urea_d1)
        self.list.append(self.hi_urea_d1)
        self.list.append(self.lo_gluc_d1)
        self.list.append(self.hi_gluc_d1)
        self.list.append(self.tbil_d1)
        self.list.append(self.intubated_8am_d1)

        self.title_list.append('study_id')
        self.title_list.append('age')
        self.title_list.append('cirr')
        self.title_list.append('cancer')
        self.title_list.append('esrd')
        self.title_list.append('lo_gcs_visual_d0')
        self.title_list.append('lo_gcs_verbal_d0')
        self.title_list.append('lo_gcs_motor_d0')
        self.title_list.append('hi_hr_24h')
        self.title_list.append('lo_hr_24h')
        self.title_list.append('hi_map_24h')
        self.title_list.append('lo_map_24h')
        self.title_list.append('hi_temp_24h')
        self.title_list.append('lo_temp_24h')
        self.title_list.append('hi_rr_24h')
        self.title_list.append('lo_rr_24h')
        self.title_list.append('hi_po2_24h')
        self.title_list.append('lo_po2_24h')
        self.title_list.append('intubated_8am_d0')
        self.title_list.append('abg_hi_fio2_24h')
        self.title_list.append('abg_lo_fio2_24h')
        self.title_list.append('ph_hi_co2_d0')
        self.title_list.append('ph_lo_co2_d0')
        self.title_list.append('hi_hct_24h')
        self.title_list.append('lo_hct_24h')
        self.title_list.append('hi_wbc_24h')
        self.title_list.append('lo_wbc_24h')
        self.title_list.append('hi_na_24h')
        self.title_list.append('lo_na_24h')
        self.title_list.append('hi_alb_d0')
        self.title_list.append('lo_alb_d0')
        self.title_list.append('tbil_d0')
        self.title_list.append('hi_gluc_d0')
        self.title_list.append('lo_gluc_d0')
        self.title_list.append('hi_urea_d0')
        self.title_list.append('lo_urea_d0')
        self.title_list.append('hi_cr_24h')
        self.title_list.append('lo_cr_24h')
        self.title_list.append('urine_out_d0')
        self.title_list.append('lo_ph_24h')
        self.title_list.append('organtx')
        self.title_list.append('sct')
        self.title_list.append('hiv')
        self.title_list.append('cd4')
        self.title_list.append('prednisone')
        self.title_list.append('pred_dose')
        
        self.title_list.append('lo_wbc_d0')
        self.title_list.append('hi_wbc_d0')
        self.title_list.append('lo_wbc_d1')
        self.title_list.append('hi_wbc_d1')
        self.title_list.append('lo_hct_d0')
        self.title_list.append('lo_hct_d1')
        self.title_list.append('hi_hct_d0')
        self.title_list.append('hi_hct_d1')
        self.title_list.append('lo_alb_d1')
        self.title_list.append('hi_alb_d1')
        self.title_list.append('urine_out_d1')
        self.title_list.append('lo_urea_d1')
        self.title_list.append('hi_urea_d1')
        self.title_list.append('lo_gluc_d1')
        self.title_list.append('hi_gluc_d1')
        self.title_list.append('tbil_d1')
        self.title_list.append('intubated_8am_d1')

        # For user input titles uncomment the code below.

        # self.numPatients = (len(CSV_file[titles[0]]))
        # self.studyID = pd.Series(CSV_file[titles[0]])
        # # Edit the following names for different file names:
        # # Demographics, Cormobidities:
        # self.age = pd.Series(CSV_file[(titles[1])])
        # self.cirrhosisStatus = pd.Series(CSV_file[titles[2]])
        # self.cancerStat = pd.Series(CSV_file[titles[3]])
        # self.endStageAKI = pd.Series(CSV_file[titles[4]])
        # self.immunoSup = pd.Series(CSV_file[titles[5]])
        # self.comaVisual = pd.Series(CSV_file[titles[6]])
        # self.comaVerbal = pd.Series(CSV_file[titles[7]])
        # self.comaMotor = pd.Series(CSV_file[titles[8]])
        # # Pulse:
        # self.pulseHigh = pd.Series(CSV_file[titles[9]])
        # self.pulseLow = pd.Series(CSV_file[titles[10]])
        # # Blood Pressure:
        # self.bpHigh = pd.Series(CSV_file[titles[11]])
        # self.bpLow = pd.Series(CSV_file[titles[12]])
        # # Temperature:(
        # self.temperatureHigh = pd.Series(CSV_file[titles[13]])
        # self.temperatureLow = pd.Series(CSV_file[titles[14]])
        # # Respiratory Rate:
        # self.respRateHigh = pd.Series(CSV_file[titles[14]])
        # self.respRateLow = pd.Series(CSV_file[titles[16]])
        # # pO2, A-aDo2, Mech Vent,
        # self.pO2High = pd.Series(CSV_file[titles[17]])
        # self.pO2Low = pd.Series(CSV_file[titles[18]])
        # self.isMechVent = pd.Series(CSV_file[titles[19]])
        # self.fiO2High = pd.Series(CSV_file[titles[20]])
        # self.fiO2Low = pd.Series(CSV_file[titles[21]])
        # self.pCO2High = pd.Series(CSV_file[titles[22]])
        # self.pCO2Low = pd.Series(CSV_file[titles[23]])
        # # Hematocrit:
        # self.critHigh = pd.Series(CSV_file[titles[24]])
        # self.critLow = pd.Series(CSV_file[titles[25]])
        # # WBC:
        # self.wbcHigh = pd.Series(CSV_file[titles[26]])
        # self.wbcLow = pd.Series(CSV_file[titles[27]])
        # # Serum Sodium:
        # self.naHigh = pd.Series(CSV_file[titles[28]])
        # self.naLow = pd.Series(CSV_file[titles[29]])
        # # Serum Albumin:
        # self.albHigh = pd.Series(CSV_file[titles[30]])
        # self.albLow = pd.Series(CSV_file[titles[31]])
        # # Serum Bilirubin:
        # self.bilirubinLevel = pd.Series(CSV_file[titles[32]])
        # # Serum Glucose:
        # self.glucHigh = pd.Series(CSV_file[titles[33]])
        # self.glucLow = pd.Series(CSV_file[titles[34]])
        # # Serum BUN (Blood Urea Nitrogen):
        # self.bunHigh = pd.Series(CSV_file[titles[35]])
        # self.bunLow = pd.Series(CSV_file[titles[36]])
        # # Acute Renal Failure Testing:
        # # Always take high on Creatinine on Day 0
        # self.crHigh = pd.Series(CSV_file[titles[37]])
        # self.crLow = pd.Series(CSV_file[titles[38]])
        # self.urineOut = pd.Series(CSV_file[titles[39]])
        # # pH and pCO2:
        # # lowest ph highest co2
        # self.pCO2pH = self.pCO2Low
        # self.pHLow = pd.Series(CSV_file[titles[40]])
        # self.organtx = pd.Series(CSV_file[titles[41]])
        # self.sct = pd.Series(CSV_file[titles[42]])
        # self.hiv = pd.Series(CSV_file[titles[43]])
        # self.cd4 = pd.Series(CSV_file[titless[44]])
        # self.prednisone = pd.Series(CSV_file[titles[45]])
        # self.pred_dose = pd.Series(CSV_file[titles[46]])
        





